-- Office Plus V58 / Supabase PostgreSQL
-- Execute once in a new Supabase project via SQL Editor.
-- Auth users are created separately. Grant membership manually (README).
BEGIN;

CREATE TABLE IF NOT EXISTS public.ks_staff_members (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'staff' CHECK (role IN ('admin','manager','staff')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.ks_is_office_member()
RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = ''
AS $$ SELECT EXISTS (
  SELECT 1 FROM public.ks_staff_members
  WHERE user_id = (SELECT auth.uid()) AND active = TRUE
); $$;

CREATE OR REPLACE FUNCTION public.ks_is_office_admin()
RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = ''
AS $$ SELECT EXISTS (
  SELECT 1 FROM public.ks_staff_members
  WHERE user_id = (SELECT auth.uid()) AND active = TRUE AND role = 'admin'
); $$;

REVOKE ALL ON FUNCTION public.ks_is_office_member() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ks_is_office_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ks_is_office_member() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ks_is_office_admin() TO authenticated;

CREATE TABLE IF NOT EXISTS public.ks_shared_state (
  scope TEXT PRIMARY KEY,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  version BIGINT NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by TEXT
);
CREATE INDEX IF NOT EXISTS ks_shared_state_updated_at_idx ON public.ks_shared_state (updated_at DESC);

CREATE TABLE IF NOT EXISTS public.ks_office_chat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT,
  sender_name TEXT NOT NULL,
  client_id TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL CHECK (char_length(message) BETWEEN 1 AND 600),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  author_uid UUID DEFAULT auth.uid()
);
CREATE INDEX IF NOT EXISTS ks_office_chat_created_at_idx ON public.ks_office_chat (created_at DESC);
CREATE INDEX IF NOT EXISTS ks_office_chat_client_id_idx ON public.ks_office_chat (client_id, id DESC);

CREATE TABLE IF NOT EXISTS public.ks_office_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  employee_id BIGINT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  dedupe_key TEXT UNIQUE,
  source_client TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  author_uid UUID DEFAULT auth.uid()
);
CREATE INDEX IF NOT EXISTS ks_office_events_created_at_idx ON public.ks_office_events (created_at DESC);
CREATE INDEX IF NOT EXISTS ks_office_events_type_idx ON public.ks_office_events (event_type, created_at DESC);

ALTER TABLE public.ks_staff_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ks_shared_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ks_office_chat ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ks_office_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY member_directory_read ON public.ks_staff_members FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id OR public.ks_is_office_admin());

CREATE POLICY state_read ON public.ks_shared_state FOR SELECT TO authenticated
USING (public.ks_is_office_member());
CREATE POLICY state_insert ON public.ks_shared_state FOR INSERT TO authenticated
WITH CHECK (public.ks_is_office_member());
CREATE POLICY state_update ON public.ks_shared_state FOR UPDATE TO authenticated
USING (public.ks_is_office_member()) WITH CHECK (public.ks_is_office_member());

CREATE POLICY chat_read ON public.ks_office_chat FOR SELECT TO authenticated
USING (public.ks_is_office_member());
CREATE POLICY chat_insert ON public.ks_office_chat FOR INSERT TO authenticated
WITH CHECK (public.ks_is_office_member() AND author_uid = (SELECT auth.uid()));
CREATE POLICY chat_clear_admin ON public.ks_office_chat FOR DELETE TO authenticated
USING (public.ks_is_office_admin());

CREATE POLICY events_read ON public.ks_office_events FOR SELECT TO authenticated
USING (public.ks_is_office_member());
CREATE POLICY events_insert ON public.ks_office_events FOR INSERT TO authenticated
WITH CHECK (public.ks_is_office_member() AND author_uid = (SELECT auth.uid()));

REVOKE ALL ON public.ks_staff_members, public.ks_shared_state, public.ks_office_chat, public.ks_office_events FROM anon;
GRANT SELECT ON public.ks_staff_members TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.ks_shared_state TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.ks_office_chat TO authenticated;
GRANT SELECT, INSERT ON public.ks_office_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.ks_office_chat_id_seq, public.ks_office_events_id_seq TO authenticated;

-- Save legacy shared-state payloads atomically and keep version numbers.
-- Clients may optionally send p_expected_version to reject stale writes.
CREATE OR REPLACE FUNCTION public.ks_save_shared_state(
  p_scope TEXT,
  p_payload JSONB,
  p_client_id TEXT DEFAULT 'web',
  p_expected_version BIGINT DEFAULT NULL
) RETURNS public.ks_shared_state LANGUAGE plpgsql SECURITY INVOKER SET search_path = public
AS $$
DECLARE r public.ks_shared_state;
BEGIN
  IF NOT public.ks_is_office_member() THEN RAISE EXCEPTION 'Access denied' USING ERRCODE='42501'; END IF;
  IF p_scope !~ '^[a-zA-Z0-9:_().-]{1,120}$' OR jsonb_typeof(p_payload) <> 'object'
    THEN RAISE EXCEPTION 'Invalid state scope or payload' USING ERRCODE='22023'; END IF;
  IF length(p_payload::TEXT) > 450000 THEN RAISE EXCEPTION 'Payload too large' USING ERRCODE='22023'; END IF;
  INSERT INTO public.ks_shared_state(scope,payload,updated_by)
  VALUES (p_scope,p_payload,left(coalesce(p_client_id,'web'),120))
  ON CONFLICT (scope) DO UPDATE SET
    payload=EXCLUDED.payload,
    updated_by=EXCLUDED.updated_by,
    version=public.ks_shared_state.version+1,
    updated_at=now()
  WHERE p_expected_version IS NULL OR public.ks_shared_state.version=p_expected_version
  RETURNING * INTO r;
  IF r.scope IS NULL THEN RAISE EXCEPTION 'State was changed by another user' USING ERRCODE='40001'; END IF;
  RETURN r;
END; $$;
REVOKE ALL ON FUNCTION public.ks_save_shared_state(TEXT,JSONB,TEXT,BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ks_save_shared_state(TEXT,JSONB,TEXT,BIGINT) TO authenticated;

-- Chat + Live Activity entry in the same database transaction.
CREATE OR REPLACE FUNCTION public.ks_post_chat(
  p_sender_id BIGINT,
  p_sender_name TEXT,
  p_client_id TEXT,
  p_message TEXT
) RETURNS JSONB LANGUAGE plpgsql SECURITY INVOKER SET search_path = public
AS $$
DECLARE r public.ks_office_chat;
BEGIN
  IF NOT public.ks_is_office_member() THEN RAISE EXCEPTION 'Access denied' USING ERRCODE='42501'; END IF;
  IF length(btrim(coalesce(p_message,''))) < 1 OR length(p_message) > 600 THEN
    RAISE EXCEPTION 'Invalid chat message' USING ERRCODE='22023';
  END IF;
  INSERT INTO public.ks_office_chat(sender_id,sender_name,client_id,message)
  VALUES (p_sender_id,left(coalesce(nullif(btrim(p_sender_name),''),'Office'),80),left(coalesce(p_client_id,'chat'),120),btrim(p_message))
  RETURNING * INTO r;
  INSERT INTO public.ks_office_events(event_type,title,message,employee_id,metadata,dedupe_key,source_client)
  VALUES ('chat_message',r.sender_name||' · Chat message',left(r.message,220),r.sender_id,
      jsonb_build_object('chatId',r.id,'clientId',r.client_id),'chat:'||r.id::TEXT,r.client_id)
  ON CONFLICT (dedupe_key) DO NOTHING;
  RETURN to_jsonb(r);
END; $$;
REVOKE ALL ON FUNCTION public.ks_post_chat(BIGINT,TEXT,TEXT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ks_post_chat(BIGINT,TEXT,TEXT,TEXT) TO authenticated;

-- Enable Postgres Changes for the live WebSocket bridge. RLS still governs visibility.
DO $$
DECLARE name TEXT;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    FOREACH name IN ARRAY ARRAY['ks_shared_state','ks_office_chat','ks_office_events'] LOOP
      IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=name) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', name);
      END IF;
    END LOOP;
  END IF;
END $$;
COMMIT;

-- Optional cleanup with Supabase Cron (run separately if pg_cron is enabled):
-- SELECT cron.schedule('office-chat-expire', '0 * * * *',
--   $$ DELETE FROM public.ks_office_chat WHERE created_at < NOW() - INTERVAL '24 hours'; $$);
